import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {recoverConfiguration} from '../scripts/recover-admin.mjs';
import {adminConfig} from '../scripts/free-admin-config.mjs';
const account='a'.repeat(32),db='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',monitor='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
async function setup(){const project=await mkdtemp(path.join(tmpdir(),'pu-recovery-'));await mkdir(path.join(project,'.cloudflare'));const calls=[],env={};const wrangler=async args=>{calls.push(args);if(args[0]==='whoami')return JSON.stringify({accounts:[{id:account,name:'Existing account'}]});if(args[0]==='d1')return JSON.stringify([{name:'pet-universe-admin',uuid:db},{name:'pet-universe-price-monitor',uuid:monitor}]);if(args[0]==='secret')return JSON.stringify((args.includes('pet-universe-admin')?['GITHUB_TOKEN','ADMIN_USERS','AUTH_PEPPER']:['DISCORD_WEBHOOK_URL','MONITOR_KEY']).map(name=>({name,type:'secret_text'})));throw Error('Forbidden mutation');};return {project,env,calls,wrangler,makeAdmin:adminConfig,log:()=>{},close:()=>rm(project,{recursive:true,force:true})};}
test('missing local configs are rebuilt from the existing account, databases and secret names without remote writes',async()=>{const f=await setup();try{const result=await recoverConfiguration(f);assert.equal(result.created.length,2);const config=JSON.parse(await readFile(path.join(f.project,'.cloudflare/admin.json'),'utf8'));assert.equal(config.account_id,account);assert.equal(config.d1_databases[0].database_id,db);assert.equal(config.keep_vars,true);assert.equal(config.limits,undefined);assert.ok(f.calls.every(args=>args[0]==='whoami'||args[0]==='d1'&&args[1]==='list'||args[0]==='secret'&&args[1]==='list'));assert.equal(f.env.CLOUDFLARE_ACCOUNT_ID,undefined);assert.deepEqual((await readdir(path.join(f.project,'.cloudflare'))).sort(),['admin.json','price-monitor.json']);}finally{await f.close();}});
test('existing configs are retained byte-for-byte without discovery requests',async()=>{const f=await setup();try{await recoverConfiguration(f);const before=await readFile(path.join(f.project,'.cloudflare/admin.json'));f.calls.length=0;assert.deepEqual((await recoverConfiguration(f)).created,[]);assert.equal(f.calls.length,0);assert.deepEqual(await readFile(path.join(f.project,'.cloudflare/admin.json')),before);}finally{await f.close();}});
test('corrupted local configuration fails without replacing it or sending remote requests',async()=>{const f=await setup();try{await writeFile(path.join(f.project,'.cloudflare/admin.json'),'{bad');await assert.rejects(()=>recoverConfiguration(f),/Uszkodzony/);assert.equal(await readFile(path.join(f.project,'.cloudflare/admin.json'),'utf8'),'{bad');assert.equal(f.calls.length,0);}finally{await f.close();}});
test('recovery cannot create a replacement worker when the existing GitHub secret is absent',async()=>{const f=await setup();try{const original=f.wrangler;f.wrangler=args=>args[0]==='secret'?Promise.resolve('[]'):original(args);await assert.rejects(()=>recoverConfiguration(f),/Nie znaleziono/);assert.deepEqual(await readdir(path.join(f.project,'.cloudflare')),[]);assert.equal(f.env.CLOUDFLARE_ACCOUNT_ID,undefined);}finally{await f.close();}});
test('conflicting account hints stop before discovery or writes',async()=>{const f=await setup();try{await writeFile(path.join(f.project,'.cloudflare/admin.json'),JSON.stringify(adminConfig({accountId:account,databaseId:db})));f.env.CLOUDFLARE_ACCOUNT_ID='b'.repeat(32);await assert.rejects(()=>recoverConfiguration(f),/rozne konta/);assert.equal(f.calls.length,0);assert.equal(f.env.CLOUDFLARE_ACCOUNT_ID,'b'.repeat(32));}finally{await f.close();}});
